version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ticketdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"

volumes:
  postgres_data: