version: '3.8'

services:
  train_postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: traindb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

volumes:
  postgres_data: