// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking.proto

package com.railway.grpc;

public final class Booking {
  private Booking() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.railway.grpc.BookingStatus}
   */
  public enum BookingStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Booked = 0;</code>
     */
    Booked(0),
    /**
     * <code>NotBooked = 1;</code>
     */
    NotBooked(1),
    /**
     * <code>YetBooked = 2;</code>
     */
    YetBooked(2),
    /**
     * <code>Unknown = 3;</code>
     */
    Unknown(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Booked = 0;</code>
     */
    public static final int Booked_VALUE = 0;
    /**
     * <code>NotBooked = 1;</code>
     */
    public static final int NotBooked_VALUE = 1;
    /**
     * <code>YetBooked = 2;</code>
     */
    public static final int YetBooked_VALUE = 2;
    /**
     * <code>Unknown = 3;</code>
     */
    public static final int Unknown_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BookingStatus valueOf(int value) {
      return forNumber(value);
    }

    public static BookingStatus forNumber(int value) {
      switch (value) {
        case 0: return Booked;
        case 1: return NotBooked;
        case 2: return YetBooked;
        case 3: return Unknown;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BookingStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        BookingStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BookingStatus>() {
            public BookingStatus findValueByNumber(int number) {
              return BookingStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.railway.grpc.Booking.getDescriptor().getEnumTypes().get(0);
    }

    private static final BookingStatus[] VALUES = values();

    public static BookingStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private BookingStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.railway.grpc.BookingStatus)
  }

  public interface GetBookingInfoAndCheckReservationRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.railway.grpc.GetBookingInfoAndCheckReservationRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 booking_id = 1;</code>
     */
    int getBookingId();
  }
  /**
   * Protobuf type {@code com.railway.grpc.GetBookingInfoAndCheckReservationRequest}
   */
  public  static final class GetBookingInfoAndCheckReservationRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.railway.grpc.GetBookingInfoAndCheckReservationRequest)
      GetBookingInfoAndCheckReservationRequestOrBuilder {
    // Use GetBookingInfoAndCheckReservationRequest.newBuilder() to construct.
    private GetBookingInfoAndCheckReservationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetBookingInfoAndCheckReservationRequest() {
      bookingId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetBookingInfoAndCheckReservationRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              bookingId_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.railway.grpc.Booking.internal_static_com_railway_grpc_GetBookingInfoAndCheckReservationRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.railway.grpc.Booking.internal_static_com_railway_grpc_GetBookingInfoAndCheckReservationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest.class, com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest.Builder.class);
    }

    public static final int BOOKING_ID_FIELD_NUMBER = 1;
    private int bookingId_;
    /**
     * <code>uint32 booking_id = 1;</code>
     */
    public int getBookingId() {
      return bookingId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (bookingId_ != 0) {
        output.writeUInt32(1, bookingId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (bookingId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, bookingId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest)) {
        return super.equals(obj);
      }
      com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest other = (com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest) obj;

      boolean result = true;
      result = result && (getBookingId()
          == other.getBookingId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BOOKING_ID_FIELD_NUMBER;
      hash = (53 * hash) + getBookingId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.railway.grpc.GetBookingInfoAndCheckReservationRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.railway.grpc.GetBookingInfoAndCheckReservationRequest)
        com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.railway.grpc.Booking.internal_static_com_railway_grpc_GetBookingInfoAndCheckReservationRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.railway.grpc.Booking.internal_static_com_railway_grpc_GetBookingInfoAndCheckReservationRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest.class, com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest.Builder.class);
      }

      // Construct using com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        bookingId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.railway.grpc.Booking.internal_static_com_railway_grpc_GetBookingInfoAndCheckReservationRequest_descriptor;
      }

      public com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest getDefaultInstanceForType() {
        return com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest.getDefaultInstance();
      }

      public com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest build() {
        com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest buildPartial() {
        com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest result = new com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest(this);
        result.bookingId_ = bookingId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest) {
          return mergeFrom((com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest other) {
        if (other == com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest.getDefaultInstance()) return this;
        if (other.getBookingId() != 0) {
          setBookingId(other.getBookingId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bookingId_ ;
      /**
       * <code>uint32 booking_id = 1;</code>
       */
      public int getBookingId() {
        return bookingId_;
      }
      /**
       * <code>uint32 booking_id = 1;</code>
       */
      public Builder setBookingId(int value) {
        
        bookingId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 booking_id = 1;</code>
       */
      public Builder clearBookingId() {
        
        bookingId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.railway.grpc.GetBookingInfoAndCheckReservationRequest)
    }

    // @@protoc_insertion_point(class_scope:com.railway.grpc.GetBookingInfoAndCheckReservationRequest)
    private static final com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest();
    }

    public static com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetBookingInfoAndCheckReservationRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetBookingInfoAndCheckReservationRequest>() {
      public GetBookingInfoAndCheckReservationRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetBookingInfoAndCheckReservationRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetBookingInfoAndCheckReservationRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetBookingInfoAndCheckReservationRequest> getParserForType() {
      return PARSER;
    }

    public com.railway.grpc.Booking.GetBookingInfoAndCheckReservationRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetBookingInfoAndCheckReservationResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.railway.grpc.GetBookingInfoAndCheckReservationResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 booking_id = 1;</code>
     */
    int getBookingId();

    /**
     * <code>string user_email = 2;</code>
     */
    java.lang.String getUserEmail();
    /**
     * <code>string user_email = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserEmailBytes();

    /**
     * <code>uint64 seat_id = 3;</code>
     */
    long getSeatId();

    /**
     * <code>.com.railway.grpc.BookingStatus status = 4;</code>
     */
    int getStatusValue();
    /**
     * <code>.com.railway.grpc.BookingStatus status = 4;</code>
     */
    com.railway.grpc.Booking.BookingStatus getStatus();
  }
  /**
   * Protobuf type {@code com.railway.grpc.GetBookingInfoAndCheckReservationResponse}
   */
  public  static final class GetBookingInfoAndCheckReservationResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.railway.grpc.GetBookingInfoAndCheckReservationResponse)
      GetBookingInfoAndCheckReservationResponseOrBuilder {
    // Use GetBookingInfoAndCheckReservationResponse.newBuilder() to construct.
    private GetBookingInfoAndCheckReservationResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetBookingInfoAndCheckReservationResponse() {
      bookingId_ = 0;
      userEmail_ = "";
      seatId_ = 0L;
      status_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetBookingInfoAndCheckReservationResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              bookingId_ = input.readUInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              userEmail_ = s;
              break;
            }
            case 24: {

              seatId_ = input.readUInt64();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.railway.grpc.Booking.internal_static_com_railway_grpc_GetBookingInfoAndCheckReservationResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.railway.grpc.Booking.internal_static_com_railway_grpc_GetBookingInfoAndCheckReservationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse.class, com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse.Builder.class);
    }

    public static final int BOOKING_ID_FIELD_NUMBER = 1;
    private int bookingId_;
    /**
     * <code>uint32 booking_id = 1;</code>
     */
    public int getBookingId() {
      return bookingId_;
    }

    public static final int USER_EMAIL_FIELD_NUMBER = 2;
    private volatile java.lang.Object userEmail_;
    /**
     * <code>string user_email = 2;</code>
     */
    public java.lang.String getUserEmail() {
      java.lang.Object ref = userEmail_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userEmail_ = s;
        return s;
      }
    }
    /**
     * <code>string user_email = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserEmailBytes() {
      java.lang.Object ref = userEmail_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEAT_ID_FIELD_NUMBER = 3;
    private long seatId_;
    /**
     * <code>uint64 seat_id = 3;</code>
     */
    public long getSeatId() {
      return seatId_;
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private int status_;
    /**
     * <code>.com.railway.grpc.BookingStatus status = 4;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.com.railway.grpc.BookingStatus status = 4;</code>
     */
    public com.railway.grpc.Booking.BookingStatus getStatus() {
      com.railway.grpc.Booking.BookingStatus result = com.railway.grpc.Booking.BookingStatus.valueOf(status_);
      return result == null ? com.railway.grpc.Booking.BookingStatus.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (bookingId_ != 0) {
        output.writeUInt32(1, bookingId_);
      }
      if (!getUserEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userEmail_);
      }
      if (seatId_ != 0L) {
        output.writeUInt64(3, seatId_);
      }
      if (status_ != com.railway.grpc.Booking.BookingStatus.Booked.getNumber()) {
        output.writeEnum(4, status_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (bookingId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, bookingId_);
      }
      if (!getUserEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userEmail_);
      }
      if (seatId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, seatId_);
      }
      if (status_ != com.railway.grpc.Booking.BookingStatus.Booked.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, status_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse)) {
        return super.equals(obj);
      }
      com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse other = (com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse) obj;

      boolean result = true;
      result = result && (getBookingId()
          == other.getBookingId());
      result = result && getUserEmail()
          .equals(other.getUserEmail());
      result = result && (getSeatId()
          == other.getSeatId());
      result = result && status_ == other.status_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BOOKING_ID_FIELD_NUMBER;
      hash = (53 * hash) + getBookingId();
      hash = (37 * hash) + USER_EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getUserEmail().hashCode();
      hash = (37 * hash) + SEAT_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSeatId());
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.railway.grpc.GetBookingInfoAndCheckReservationResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.railway.grpc.GetBookingInfoAndCheckReservationResponse)
        com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.railway.grpc.Booking.internal_static_com_railway_grpc_GetBookingInfoAndCheckReservationResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.railway.grpc.Booking.internal_static_com_railway_grpc_GetBookingInfoAndCheckReservationResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse.class, com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse.Builder.class);
      }

      // Construct using com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        bookingId_ = 0;

        userEmail_ = "";

        seatId_ = 0L;

        status_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.railway.grpc.Booking.internal_static_com_railway_grpc_GetBookingInfoAndCheckReservationResponse_descriptor;
      }

      public com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse getDefaultInstanceForType() {
        return com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse.getDefaultInstance();
      }

      public com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse build() {
        com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse buildPartial() {
        com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse result = new com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse(this);
        result.bookingId_ = bookingId_;
        result.userEmail_ = userEmail_;
        result.seatId_ = seatId_;
        result.status_ = status_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse) {
          return mergeFrom((com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse other) {
        if (other == com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse.getDefaultInstance()) return this;
        if (other.getBookingId() != 0) {
          setBookingId(other.getBookingId());
        }
        if (!other.getUserEmail().isEmpty()) {
          userEmail_ = other.userEmail_;
          onChanged();
        }
        if (other.getSeatId() != 0L) {
          setSeatId(other.getSeatId());
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bookingId_ ;
      /**
       * <code>uint32 booking_id = 1;</code>
       */
      public int getBookingId() {
        return bookingId_;
      }
      /**
       * <code>uint32 booking_id = 1;</code>
       */
      public Builder setBookingId(int value) {
        
        bookingId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 booking_id = 1;</code>
       */
      public Builder clearBookingId() {
        
        bookingId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object userEmail_ = "";
      /**
       * <code>string user_email = 2;</code>
       */
      public java.lang.String getUserEmail() {
        java.lang.Object ref = userEmail_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userEmail_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_email = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserEmailBytes() {
        java.lang.Object ref = userEmail_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userEmail_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_email = 2;</code>
       */
      public Builder setUserEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userEmail_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string user_email = 2;</code>
       */
      public Builder clearUserEmail() {
        
        userEmail_ = getDefaultInstance().getUserEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string user_email = 2;</code>
       */
      public Builder setUserEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userEmail_ = value;
        onChanged();
        return this;
      }

      private long seatId_ ;
      /**
       * <code>uint64 seat_id = 3;</code>
       */
      public long getSeatId() {
        return seatId_;
      }
      /**
       * <code>uint64 seat_id = 3;</code>
       */
      public Builder setSeatId(long value) {
        
        seatId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 seat_id = 3;</code>
       */
      public Builder clearSeatId() {
        
        seatId_ = 0L;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.com.railway.grpc.BookingStatus status = 4;</code>
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.com.railway.grpc.BookingStatus status = 4;</code>
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.railway.grpc.BookingStatus status = 4;</code>
       */
      public com.railway.grpc.Booking.BookingStatus getStatus() {
        com.railway.grpc.Booking.BookingStatus result = com.railway.grpc.Booking.BookingStatus.valueOf(status_);
        return result == null ? com.railway.grpc.Booking.BookingStatus.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.railway.grpc.BookingStatus status = 4;</code>
       */
      public Builder setStatus(com.railway.grpc.Booking.BookingStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.railway.grpc.BookingStatus status = 4;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.railway.grpc.GetBookingInfoAndCheckReservationResponse)
    }

    // @@protoc_insertion_point(class_scope:com.railway.grpc.GetBookingInfoAndCheckReservationResponse)
    private static final com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse();
    }

    public static com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetBookingInfoAndCheckReservationResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetBookingInfoAndCheckReservationResponse>() {
      public GetBookingInfoAndCheckReservationResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetBookingInfoAndCheckReservationResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetBookingInfoAndCheckReservationResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetBookingInfoAndCheckReservationResponse> getParserForType() {
      return PARSER;
    }

    public com.railway.grpc.Booking.GetBookingInfoAndCheckReservationResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RemoveBookingRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.railway.grpc.RemoveBookingRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 booking_id = 1;</code>
     */
    int getBookingId();
  }
  /**
   * Protobuf type {@code com.railway.grpc.RemoveBookingRequest}
   */
  public  static final class RemoveBookingRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.railway.grpc.RemoveBookingRequest)
      RemoveBookingRequestOrBuilder {
    // Use RemoveBookingRequest.newBuilder() to construct.
    private RemoveBookingRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RemoveBookingRequest() {
      bookingId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RemoveBookingRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              bookingId_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.railway.grpc.Booking.internal_static_com_railway_grpc_RemoveBookingRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.railway.grpc.Booking.internal_static_com_railway_grpc_RemoveBookingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.railway.grpc.Booking.RemoveBookingRequest.class, com.railway.grpc.Booking.RemoveBookingRequest.Builder.class);
    }

    public static final int BOOKING_ID_FIELD_NUMBER = 1;
    private int bookingId_;
    /**
     * <code>uint32 booking_id = 1;</code>
     */
    public int getBookingId() {
      return bookingId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (bookingId_ != 0) {
        output.writeUInt32(1, bookingId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (bookingId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, bookingId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.railway.grpc.Booking.RemoveBookingRequest)) {
        return super.equals(obj);
      }
      com.railway.grpc.Booking.RemoveBookingRequest other = (com.railway.grpc.Booking.RemoveBookingRequest) obj;

      boolean result = true;
      result = result && (getBookingId()
          == other.getBookingId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BOOKING_ID_FIELD_NUMBER;
      hash = (53 * hash) + getBookingId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.railway.grpc.Booking.RemoveBookingRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.railway.grpc.Booking.RemoveBookingRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.railway.grpc.Booking.RemoveBookingRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.railway.grpc.Booking.RemoveBookingRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.railway.grpc.Booking.RemoveBookingRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.railway.grpc.Booking.RemoveBookingRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.railway.grpc.Booking.RemoveBookingRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.railway.grpc.Booking.RemoveBookingRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.railway.grpc.Booking.RemoveBookingRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.railway.grpc.Booking.RemoveBookingRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.railway.grpc.Booking.RemoveBookingRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.railway.grpc.Booking.RemoveBookingRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.railway.grpc.Booking.RemoveBookingRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.railway.grpc.RemoveBookingRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.railway.grpc.RemoveBookingRequest)
        com.railway.grpc.Booking.RemoveBookingRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.railway.grpc.Booking.internal_static_com_railway_grpc_RemoveBookingRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.railway.grpc.Booking.internal_static_com_railway_grpc_RemoveBookingRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.railway.grpc.Booking.RemoveBookingRequest.class, com.railway.grpc.Booking.RemoveBookingRequest.Builder.class);
      }

      // Construct using com.railway.grpc.Booking.RemoveBookingRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        bookingId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.railway.grpc.Booking.internal_static_com_railway_grpc_RemoveBookingRequest_descriptor;
      }

      public com.railway.grpc.Booking.RemoveBookingRequest getDefaultInstanceForType() {
        return com.railway.grpc.Booking.RemoveBookingRequest.getDefaultInstance();
      }

      public com.railway.grpc.Booking.RemoveBookingRequest build() {
        com.railway.grpc.Booking.RemoveBookingRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.railway.grpc.Booking.RemoveBookingRequest buildPartial() {
        com.railway.grpc.Booking.RemoveBookingRequest result = new com.railway.grpc.Booking.RemoveBookingRequest(this);
        result.bookingId_ = bookingId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.railway.grpc.Booking.RemoveBookingRequest) {
          return mergeFrom((com.railway.grpc.Booking.RemoveBookingRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.railway.grpc.Booking.RemoveBookingRequest other) {
        if (other == com.railway.grpc.Booking.RemoveBookingRequest.getDefaultInstance()) return this;
        if (other.getBookingId() != 0) {
          setBookingId(other.getBookingId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.railway.grpc.Booking.RemoveBookingRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.railway.grpc.Booking.RemoveBookingRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bookingId_ ;
      /**
       * <code>uint32 booking_id = 1;</code>
       */
      public int getBookingId() {
        return bookingId_;
      }
      /**
       * <code>uint32 booking_id = 1;</code>
       */
      public Builder setBookingId(int value) {
        
        bookingId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 booking_id = 1;</code>
       */
      public Builder clearBookingId() {
        
        bookingId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.railway.grpc.RemoveBookingRequest)
    }

    // @@protoc_insertion_point(class_scope:com.railway.grpc.RemoveBookingRequest)
    private static final com.railway.grpc.Booking.RemoveBookingRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.railway.grpc.Booking.RemoveBookingRequest();
    }

    public static com.railway.grpc.Booking.RemoveBookingRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RemoveBookingRequest>
        PARSER = new com.google.protobuf.AbstractParser<RemoveBookingRequest>() {
      public RemoveBookingRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RemoveBookingRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RemoveBookingRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RemoveBookingRequest> getParserForType() {
      return PARSER;
    }

    public com.railway.grpc.Booking.RemoveBookingRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RemoveBookingResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.railway.grpc.RemoveBookingResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool success = 1;</code>
     */
    boolean getSuccess();

    /**
     * <code>string message = 2;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code com.railway.grpc.RemoveBookingResponse}
   */
  public  static final class RemoveBookingResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.railway.grpc.RemoveBookingResponse)
      RemoveBookingResponseOrBuilder {
    // Use RemoveBookingResponse.newBuilder() to construct.
    private RemoveBookingResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RemoveBookingResponse() {
      success_ = false;
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RemoveBookingResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              success_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.railway.grpc.Booking.internal_static_com_railway_grpc_RemoveBookingResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.railway.grpc.Booking.internal_static_com_railway_grpc_RemoveBookingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.railway.grpc.Booking.RemoveBookingResponse.class, com.railway.grpc.Booking.RemoveBookingResponse.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.railway.grpc.Booking.RemoveBookingResponse)) {
        return super.equals(obj);
      }
      com.railway.grpc.Booking.RemoveBookingResponse other = (com.railway.grpc.Booking.RemoveBookingResponse) obj;

      boolean result = true;
      result = result && (getSuccess()
          == other.getSuccess());
      result = result && getMessage()
          .equals(other.getMessage());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.railway.grpc.Booking.RemoveBookingResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.railway.grpc.Booking.RemoveBookingResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.railway.grpc.Booking.RemoveBookingResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.railway.grpc.Booking.RemoveBookingResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.railway.grpc.Booking.RemoveBookingResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.railway.grpc.Booking.RemoveBookingResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.railway.grpc.Booking.RemoveBookingResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.railway.grpc.Booking.RemoveBookingResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.railway.grpc.Booking.RemoveBookingResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.railway.grpc.Booking.RemoveBookingResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.railway.grpc.Booking.RemoveBookingResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.railway.grpc.Booking.RemoveBookingResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.railway.grpc.Booking.RemoveBookingResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.railway.grpc.RemoveBookingResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.railway.grpc.RemoveBookingResponse)
        com.railway.grpc.Booking.RemoveBookingResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.railway.grpc.Booking.internal_static_com_railway_grpc_RemoveBookingResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.railway.grpc.Booking.internal_static_com_railway_grpc_RemoveBookingResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.railway.grpc.Booking.RemoveBookingResponse.class, com.railway.grpc.Booking.RemoveBookingResponse.Builder.class);
      }

      // Construct using com.railway.grpc.Booking.RemoveBookingResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        success_ = false;

        message_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.railway.grpc.Booking.internal_static_com_railway_grpc_RemoveBookingResponse_descriptor;
      }

      public com.railway.grpc.Booking.RemoveBookingResponse getDefaultInstanceForType() {
        return com.railway.grpc.Booking.RemoveBookingResponse.getDefaultInstance();
      }

      public com.railway.grpc.Booking.RemoveBookingResponse build() {
        com.railway.grpc.Booking.RemoveBookingResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.railway.grpc.Booking.RemoveBookingResponse buildPartial() {
        com.railway.grpc.Booking.RemoveBookingResponse result = new com.railway.grpc.Booking.RemoveBookingResponse(this);
        result.success_ = success_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.railway.grpc.Booking.RemoveBookingResponse) {
          return mergeFrom((com.railway.grpc.Booking.RemoveBookingResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.railway.grpc.Booking.RemoveBookingResponse other) {
        if (other == com.railway.grpc.Booking.RemoveBookingResponse.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.railway.grpc.Booking.RemoveBookingResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.railway.grpc.Booking.RemoveBookingResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean success_ ;
      /**
       * <code>bool success = 1;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 1;</code>
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 1;</code>
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 2;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.railway.grpc.RemoveBookingResponse)
    }

    // @@protoc_insertion_point(class_scope:com.railway.grpc.RemoveBookingResponse)
    private static final com.railway.grpc.Booking.RemoveBookingResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.railway.grpc.Booking.RemoveBookingResponse();
    }

    public static com.railway.grpc.Booking.RemoveBookingResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RemoveBookingResponse>
        PARSER = new com.google.protobuf.AbstractParser<RemoveBookingResponse>() {
      public RemoveBookingResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RemoveBookingResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RemoveBookingResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RemoveBookingResponse> getParserForType() {
      return PARSER;
    }

    public com.railway.grpc.Booking.RemoveBookingResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_railway_grpc_GetBookingInfoAndCheckReservationRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_railway_grpc_GetBookingInfoAndCheckReservationRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_railway_grpc_GetBookingInfoAndCheckReservationResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_railway_grpc_GetBookingInfoAndCheckReservationResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_railway_grpc_RemoveBookingRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_railway_grpc_RemoveBookingRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_railway_grpc_RemoveBookingResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_railway_grpc_RemoveBookingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rbooking.proto\022\020com.railway.grpc\">\n(Get" +
      "BookingInfoAndCheckReservationRequest\022\022\n" +
      "\nbooking_id\030\001 \001(\r\"\225\001\n)GetBookingInfoAndC" +
      "heckReservationResponse\022\022\n\nbooking_id\030\001 " +
      "\001(\r\022\022\n\nuser_email\030\002 \001(\t\022\017\n\007seat_id\030\003 \001(\004" +
      "\022/\n\006status\030\004 \001(\0162\037.com.railway.grpc.Book" +
      "ingStatus\"*\n\024RemoveBookingRequest\022\022\n\nboo" +
      "king_id\030\001 \001(\r\"9\n\025RemoveBookingResponse\022\017" +
      "\n\007success\030\001 \001(\010\022\017\n\007message\030\002 \001(\t*F\n\rBook" +
      "ingStatus\022\n\n\006Booked\020\000\022\r\n\tNotBooked\020\001\022\r\n\t",
      "YetBooked\020\002\022\013\n\007Unknown\020\0032\221\002\n\016BookingServ" +
      "ice\022\234\001\n!GetBookingInfoAndCheckReservatio" +
      "n\022:.com.railway.grpc.GetBookingInfoAndCh" +
      "eckReservationRequest\032;.com.railway.grpc" +
      ".GetBookingInfoAndCheckReservationRespon" +
      "se\022`\n\rRemoveBooking\022&.com.railway.grpc.R" +
      "emoveBookingRequest\032\'.com.railway.grpc.R" +
      "emoveBookingResponseb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_railway_grpc_GetBookingInfoAndCheckReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_railway_grpc_GetBookingInfoAndCheckReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_railway_grpc_GetBookingInfoAndCheckReservationRequest_descriptor,
        new java.lang.String[] { "BookingId", });
    internal_static_com_railway_grpc_GetBookingInfoAndCheckReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_railway_grpc_GetBookingInfoAndCheckReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_railway_grpc_GetBookingInfoAndCheckReservationResponse_descriptor,
        new java.lang.String[] { "BookingId", "UserEmail", "SeatId", "Status", });
    internal_static_com_railway_grpc_RemoveBookingRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_railway_grpc_RemoveBookingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_railway_grpc_RemoveBookingRequest_descriptor,
        new java.lang.String[] { "BookingId", });
    internal_static_com_railway_grpc_RemoveBookingResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_railway_grpc_RemoveBookingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_railway_grpc_RemoveBookingResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
