version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
  paymentservice:
    build: .
    image: railway/payment-service:1.0-SNAPSHOT
    depends_on:
      - db
    ports:
      - "8081:8080"
volumes:
  postgres_data: