version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: bookingdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"

  bookingservice:
    build: .
    image: railway/booking-service:1.0-SNAPSHOT
    depends_on:
      - db
    ports:
      - "8082:8080"
volumes:
  postgres_data: