version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ticketdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  ticketservice:
    build: .
    image: railway/ticket-service:1.0-SNAPSHOT
    depends_on:
      - db
    ports:
      - "8080:8080"
volumes:
  postgres_data: